# Numpy Assignment

In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1.
Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [8]:
# List
list = [1,2,3,4,5]
type(list)

list

In [9]:
import pandas as pd

In [11]:
# Array_List
Array_list = np.array([1,2,3,4,5])
type(Array_list)

numpy.ndarray

# Q2.
Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [16]:
# Data type of list element

In [15]:
list = [1,2,3,4,5]
for i in list:
    print(i,"data type:", type(i) )

1 data type: <class 'int'>
2 data type: <class 'int'>
3 data type: <class 'int'>
4 data type: <class 'int'>
5 data type: <class 'int'>


In [17]:
# Data type of Array_list element

In [18]:
Array_list = np.array([1,2,3,4,5])
for i in Array_list:
    print(i,"data type:", type(i) )
    

1 data type: <class 'numpy.int64'>
2 data type: <class 'numpy.int64'>
3 data type: <class 'numpy.int64'>
4 data type: <class 'numpy.int64'>
5 data type: <class 'numpy.int64'>


# Q3.
Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [19]:
list = [1,2,3,4,5]
for i in list:
    print(i,"data type:", type(i) )

1 data type: <class 'int'>
2 data type: <class 'int'>
3 data type: <class 'int'>
4 data type: <class 'int'>
5 data type: <class 'int'>


In [20]:
Array_list = np.array([1,2,3,4,5])
for i in Array_list:
    print(i,"data type:", type(i) )

1 data type: <class 'numpy.int64'>
2 data type: <class 'numpy.int64'>
3 data type: <class 'numpy.int64'>
4 data type: <class 'numpy.int64'>
5 data type: <class 'numpy.int64'>


# Q4. 
Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [21]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [22]:
arr_list = np.array(object=num_list)

In [23]:
arr_list

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# Shape

In [25]:
np.shape(arr_list)

(2, 3)

In [27]:
# size

In [28]:
np.size(arr_list)

6

# Q5.
Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [30]:
var = np.zeros([3,3])

In [31]:
var

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.shape(var)

(3, 3)

In [33]:
np.size(var)

9

# Q6.
Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [34]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])